# Generated by Django 5.1.4 on 2025-01-07 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('normal', '普通用户')], max_length=10, verbose_name='角色')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='失败尝试次数')),
                ('lockout_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定截止时间')),
            ],
            options={
                'unique_together': {('phone', 'role')},
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
                ('is_staff', models.BooleanField(default=True, verbose_name='是否为员工')),
                ('groups', models.ManyToManyField(blank=True, related_name='admin_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='admin_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': '管理员用户',
                'verbose_name_plural': '管理员用户',
                'unique_together': {('phone',)},
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
                ('groups', models.ManyToManyField(blank=True, related_name='staff_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='staff_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': '普通用户',
                'verbose_name_plural': '普通用户',
                'unique_together': {('phone',)},
            },
        ),
    ]
